### ISSUE TITLE
there is a bug in function "saturation"

### ISSUE THREAD

**Issue by fourwq** [Rachine/ExposureFusion#1]
def saturation(self):
        """Function that returns the Saturation map"""
        red_canal = self.array[:, :, 0]
        green_canal = self.array[:, :, 1]
        blue_canal = self.array[:, :, 2]
        mean = red_canal + green_canal + blue_canal / 3.0  //here need  parentheses
        saturation = np.sqrt(((red_canal - mean)**2 + (green_canal - mean)**2 + (blue_canal - mean)**2)/3)
        return saturation

**Comment by Rachine** [comment]
yes you are right, can you make a pr?
